-- ============================================
-- Coğrafi İşaret Watchlist + Alerts Schema
-- Adds:
--   * cografi_watchlist_mt   (user-tracked items — four watch types)
--   * cografi_alerts_mt      (matches generated by the scanner)
--
-- Mirrors the patent + design watchlist tables but adapted for cografi:
--   * 4 watch types: holder | reference | region | lifecycle
--   * 'region' is cografi's headline use case — alert when new GIs
--     appear matching a watched geographical_boundary trigram pattern
--   * 'lifecycle' tracks an existing registration_no — alerts when an
--     art42 change request, art42 finalized change, or correction
--     targets that registration. No equivalent in patent watchlist.
--   * 'reference' clones text_embedding from the reference cografi
--     record at watchlist-create time (1024-dim e5-large halfvec).
--   * 'holder' matches by holder_id against the global holders table
--     (TPECLIENT IDs are shared across all four registries).
--
-- Idempotent: safe to run multiple times.
-- ============================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "vector";

-- ============================================
-- 1. cografi_watchlist_mt — items the user is tracking
-- ============================================
CREATE TABLE IF NOT EXISTS cografi_watchlist_mt (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id         UUID REFERENCES users(id) ON DELETE SET NULL,

    -- Discriminator
    watch_type      VARCHAR(20) NOT NULL
                    CHECK (watch_type IN ('holder', 'reference', 'region', 'lifecycle')),

    -- User-friendly label (e.g. "Karapınar bölgesi" or "Erzurum Belediyesi")
    label           VARCHAR(500) NOT NULL,
    description     TEXT,

    -- Holder-watch fields (NULL when watch_type != 'holder')
    holder_name           VARCHAR(500),
    holder_id             UUID REFERENCES holders(id) ON DELETE SET NULL,
    holder_tpe_client_id  VARCHAR(255),

    -- Reference-watch fields (NULL when watch_type != 'reference')
    -- Reference can be either an existing cografi record (FK) or a
    -- free-text query the user typed; reference_embedding is computed
    -- (cloned from record.text_embedding OR encoded from query) at
    -- watchlist-create time so scan-time retrieval is a pure cosine
    -- query against cografi_records.text_embedding.
    reference_record_id   UUID REFERENCES cografi_records(id) ON DELETE SET NULL,
    reference_query       TEXT,
    reference_embedding   halfvec(1024),

    -- Region-watch fields (NULL when watch_type != 'region')
    -- region_query is matched via trigram + ILIKE against
    -- cografi_records.geographical_boundary at scan time. Optional
    -- region_terms array supports multi-region watches (e.g. all of
    -- "Konya", "Karaman", "Aksaray") via ANY-match.
    region_query    TEXT,
    region_terms    TEXT[] DEFAULT '{}'::TEXT[],

    -- Lifecycle-watch fields (NULL when watch_type != 'lifecycle')
    -- Watches a specific registration_no — alerts fire when any new
    -- record (typically art42 change request, art42 finalized, or
    -- correction) carries this registration_no in
    -- existing_registration_no, registration_no, or
    -- correction_referenced_record_id.
    lifecycle_registration_no INTEGER,

    -- Optional narrowing filters (applied across all watch types)
    section_keys   TEXT[] DEFAULT '{}'::TEXT[],   -- e.g. ['examined','registered']
    record_types   TEXT[] DEFAULT '{}'::TEXT[],   -- e.g. ['GI']
    gi_type        VARCHAR(100),

    -- Customer's own registration (self-conflict exclusion at scan time)
    customer_application_no VARCHAR(50),
    customer_registration_no INTEGER,

    -- Monitoring + notification preferences
    similarity_threshold REAL DEFAULT 0.50
                         CHECK (similarity_threshold BETWEEN 0.0 AND 1.0),
    alert_email          BOOLEAN DEFAULT TRUE,
    alert_webhook        BOOLEAN DEFAULT FALSE,
    webhook_url          TEXT,
    alert_frequency      VARCHAR(20) DEFAULT 'daily'
                         CHECK (alert_frequency IN ('immediate','daily','weekly')),

    -- Lifecycle metadata
    tags          TEXT[] DEFAULT '{}',
    priority      VARCHAR(10) DEFAULT 'medium'
                  CHECK (priority IN ('low','medium','high')),
    is_active     BOOLEAN DEFAULT TRUE,
    last_scan_at  TIMESTAMP,
    created_at    TIMESTAMP DEFAULT NOW(),
    updated_at    TIMESTAMP DEFAULT NOW(),

    -- watch_type drives which columns must be set
    CONSTRAINT chk_holder_watch_has_holder
        CHECK (watch_type <> 'holder' OR (
            holder_name IS NOT NULL OR holder_id IS NOT NULL OR holder_tpe_client_id IS NOT NULL
        )),
    CONSTRAINT chk_reference_watch_has_reference
        CHECK (watch_type <> 'reference' OR (
            reference_record_id IS NOT NULL OR reference_query IS NOT NULL
        )),
    CONSTRAINT chk_region_watch_has_region
        CHECK (watch_type <> 'region' OR (
            region_query IS NOT NULL OR array_length(region_terms, 1) > 0
        )),
    CONSTRAINT chk_lifecycle_watch_has_registration
        CHECK (watch_type <> 'lifecycle' OR lifecycle_registration_no IS NOT NULL),
    CONSTRAINT chk_webhook_url_when_enabled
        CHECK (NOT alert_webhook OR webhook_url IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_cwl_org              ON cografi_watchlist_mt(organization_id);
CREATE INDEX IF NOT EXISTS idx_cwl_user             ON cografi_watchlist_mt(user_id);
CREATE INDEX IF NOT EXISTS idx_cwl_active           ON cografi_watchlist_mt(organization_id, is_active);
CREATE INDEX IF NOT EXISTS idx_cwl_watch_type       ON cografi_watchlist_mt(organization_id, watch_type);
CREATE INDEX IF NOT EXISTS idx_cwl_holder_id        ON cografi_watchlist_mt(holder_id) WHERE holder_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cwl_holder_tpe       ON cografi_watchlist_mt(holder_tpe_client_id) WHERE holder_tpe_client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cwl_holder_name_trgm ON cografi_watchlist_mt USING GIST (holder_name gist_trgm_ops)
    WHERE holder_name IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cwl_region_query_trgm ON cografi_watchlist_mt USING GIST (region_query gist_trgm_ops)
    WHERE region_query IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cwl_region_terms     ON cografi_watchlist_mt USING GIN (region_terms);
CREATE INDEX IF NOT EXISTS idx_cwl_lifecycle_reg    ON cografi_watchlist_mt(lifecycle_registration_no)
    WHERE lifecycle_registration_no IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cwl_section_keys     ON cografi_watchlist_mt USING GIN (section_keys);
CREATE INDEX IF NOT EXISTS idx_cwl_ref_vec          ON cografi_watchlist_mt USING hnsw (reference_embedding halfvec_cosine_ops)
    WITH (m=16, ef_construction=200) WHERE reference_embedding IS NOT NULL;

-- ============================================
-- 2. cografi_alerts_mt — matches generated by the scanner
-- ============================================
-- Conflicting fields are denormalized so an alert survives the
-- referenced cografi_records row being deleted (e.g. if an extractor
-- re-run dedups a record on a refreshed natural key).
CREATE TABLE IF NOT EXISTS cografi_alerts_mt (
    id                 UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    watchlist_item_id  UUID NOT NULL REFERENCES cografi_watchlist_mt(id) ON DELETE CASCADE,
    user_id            UUID REFERENCES users(id) ON DELETE SET NULL,
    organization_id    UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    -- Conflict reference (denormalized so alerts survive record deletion)
    conflicting_record_id        UUID REFERENCES cografi_records(id) ON DELETE SET NULL,
    conflicting_section_key      VARCHAR(50),
    conflicting_record_type      VARCHAR(10),
    conflicting_application_no   VARCHAR(50),
    conflicting_registration_no  INTEGER,
    conflicting_existing_registration_no INTEGER,
    conflicting_name             TEXT,
    conflicting_gi_type          VARCHAR(100),
    conflicting_geographical_boundary TEXT,
    conflicting_bulletin_no      INTEGER,
    conflicting_bulletin_date    DATE,
    conflicting_application_date DATE,
    conflicting_registration_date DATE,

    -- Match diagnostics
    match_type           VARCHAR(40)
                         CHECK (match_type IN (
                             'holder',
                             'reference_text', 'reference_embedding', 'reference_hybrid',
                             'region',
                             'lifecycle_change_request', 'lifecycle_finalized', 'lifecycle_correction'
                         )),
    overall_similarity_score REAL NOT NULL,
    text_similarity_score    REAL,
    embedding_similarity_score REAL,
    region_similarity_score    REAL,
    score_details            JSONB DEFAULT '{}'::jsonb,
    overlapping_section_keys TEXT[] DEFAULT '{}',

    -- Lifecycle
    severity        VARCHAR(20) DEFAULT 'medium' CHECK (severity IN ('low','medium','high','critical')),
    status          VARCHAR(20) DEFAULT 'new'    CHECK (status IN ('new','seen','acknowledged','resolved','dismissed')),
    alert_type      VARCHAR(20) DEFAULT 'conflict' CHECK (alert_type IN ('conflict','event')),

    -- Notification delivery flags
    email_sent      BOOLEAN DEFAULT FALSE,
    email_sent_at   TIMESTAMP,
    webhook_sent    BOOLEAN DEFAULT FALSE,
    webhook_sent_at TIMESTAMP,
    webhook_response_code INTEGER,

    -- Acknowledgement workflow
    acknowledged_at  TIMESTAMP,
    acknowledged_by  UUID REFERENCES users(id) ON DELETE SET NULL,
    resolved_at      TIMESTAMP,
    resolved_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    resolution_notes TEXT,

    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Natural dedup: one alert per (watchlist_item, conflicting_record).
-- conflicting_record_id can be NULL post-cascade so the unique scope is partial.
CREATE UNIQUE INDEX IF NOT EXISTS uq_cografi_alerts_pair
    ON cografi_alerts_mt (watchlist_item_id, conflicting_record_id)
    WHERE conflicting_record_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cal_org           ON cografi_alerts_mt(organization_id);
CREATE INDEX IF NOT EXISTS idx_cal_watchlist     ON cografi_alerts_mt(watchlist_item_id);
CREATE INDEX IF NOT EXISTS idx_cal_status        ON cografi_alerts_mt(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_cal_severity      ON cografi_alerts_mt(organization_id, severity);
CREATE INDEX IF NOT EXISTS idx_cal_created       ON cografi_alerts_mt(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cal_match_type    ON cografi_alerts_mt(organization_id, match_type);
CREATE INDEX IF NOT EXISTS idx_cal_pending_email
    ON cografi_alerts_mt(id) WHERE email_sent = FALSE;
CREATE INDEX IF NOT EXISTS idx_cal_pending_webhook
    ON cografi_alerts_mt(id) WHERE webhook_sent = FALSE;

-- ============================================
-- Rollback (uncomment to drop both tables — destructive)
-- ============================================
-- DROP TABLE IF EXISTS cografi_alerts_mt CASCADE;
-- DROP TABLE IF EXISTS cografi_watchlist_mt CASCADE;
