-- ============================================
-- Design Watchlist + Alerts Schema
-- Adds:
--   * design_watchlist_mt  (user-tracked designs)
--   * design_alerts_mt     (matches generated by the scanner)
-- Mirrors the multi-tenant trademark watchlist tables (watchlist_mt/alerts_mt)
-- but with design-specific columns: Locarno classes (not Nice), DINOv2 ViT-L/14
-- 1024-d embeddings (not 768-d), and no phonetic/translation similarity columns.
--
-- Idempotent: safe to run multiple times.
-- ============================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "vector";

-- ============================================
-- 1. design_watchlist_mt — items the user is tracking
-- ============================================
CREATE TABLE IF NOT EXISTS design_watchlist_mt (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id         UUID REFERENCES users(id) ON DELETE SET NULL,

    -- Label + classification
    product_name    VARCHAR(500) NOT NULL,
    locarno_classes TEXT[] NOT NULL DEFAULT '{}',
    description     TEXT,

    -- User's own design record (self-conflict exclusion)
    customer_application_no  VARCHAR(50),
    customer_registration_no VARCHAR(50),

    -- Optional reference: copy embedding directly from an existing design
    reference_design_id UUID REFERENCES designs(id) ON DELETE SET NULL,

    -- Reference image + embeddings (set by image upload endpoint)
    image_path          TEXT,
    dinov2_embedding    halfvec(1024),
    clip_embedding      halfvec(512),
    color_histogram     halfvec(512),

    -- Monitoring + notification preferences
    similarity_threshold REAL DEFAULT 0.50 CHECK (similarity_threshold BETWEEN 0.0 AND 1.0),
    monitor_text         BOOLEAN DEFAULT TRUE,
    monitor_visual       BOOLEAN DEFAULT TRUE,
    alert_email          BOOLEAN DEFAULT TRUE,
    alert_webhook        BOOLEAN DEFAULT FALSE,
    webhook_url          TEXT,
    alert_frequency      VARCHAR(20) DEFAULT 'daily' CHECK (alert_frequency IN ('immediate','daily','weekly')),

    -- Lifecycle
    tags          TEXT[] DEFAULT '{}',
    priority      VARCHAR(10) DEFAULT 'medium' CHECK (priority IN ('low','medium','high')),
    is_active     BOOLEAN DEFAULT TRUE,
    last_scan_at  TIMESTAMP,
    created_at    TIMESTAMP DEFAULT NOW(),
    updated_at    TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dwl_org           ON design_watchlist_mt(organization_id);
CREATE INDEX IF NOT EXISTS idx_dwl_user          ON design_watchlist_mt(user_id);
CREATE INDEX IF NOT EXISTS idx_dwl_active        ON design_watchlist_mt(organization_id, is_active);
CREATE INDEX IF NOT EXISTS idx_dwl_product_trgm  ON design_watchlist_mt USING GIST (product_name gist_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_dwl_locarno       ON design_watchlist_mt USING GIN (locarno_classes);
CREATE INDEX IF NOT EXISTS idx_dwl_dinov2_vec    ON design_watchlist_mt USING hnsw (dinov2_embedding halfvec_cosine_ops)
    WITH (m=16, ef_construction=200) WHERE dinov2_embedding IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_dwl_clip_vec      ON design_watchlist_mt USING hnsw (clip_embedding halfvec_cosine_ops)
    WITH (m=16, ef_construction=200) WHERE clip_embedding IS NOT NULL;

-- ============================================
-- 2. design_alerts_mt — matches generated by the scanner
-- ============================================
CREATE TABLE IF NOT EXISTS design_alerts_mt (
    id                 UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    watchlist_item_id  UUID NOT NULL REFERENCES design_watchlist_mt(id) ON DELETE CASCADE,
    user_id            UUID REFERENCES users(id) ON DELETE SET NULL,
    organization_id    UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    -- Conflict reference (fully denormalized so alerts survive design row deletion)
    conflicting_design_id        UUID REFERENCES designs(id) ON DELETE SET NULL,
    conflicting_application_no   VARCHAR(50),
    conflicting_registration_no  VARCHAR(50),
    conflicting_product_name     TEXT,
    conflicting_locarno_classes  TEXT[] DEFAULT '{}',
    conflicting_holder_name      TEXT,
    conflicting_image_path       TEXT,
    conflicting_bulletin_no      VARCHAR(10),
    conflicting_bulletin_date    DATE,
    opposition_deadline          DATE,

    -- Per-signal scores (0..1)
    overall_similarity_score REAL NOT NULL,
    dino_similarity_score    REAL,
    clip_similarity_score    REAL,
    color_similarity_score   REAL,
    text_similarity_score    REAL,
    score_details            JSONB DEFAULT '{}'::jsonb,
    overlapping_classes      TEXT[] DEFAULT '{}',

    -- Lifecycle
    severity        VARCHAR(20) DEFAULT 'medium' CHECK (severity IN ('low','medium','high','critical')),
    status          VARCHAR(20) DEFAULT 'new'    CHECK (status IN ('new','seen','acknowledged','resolved','dismissed')),
    alert_type      VARCHAR(20) DEFAULT 'conflict' CHECK (alert_type IN ('conflict','event')),
    source_type     VARCHAR(50),
    source_reference VARCHAR(100),

    email_sent      BOOLEAN DEFAULT FALSE,
    email_sent_at   TIMESTAMP,

    acknowledged_at TIMESTAMP,
    acknowledged_by UUID REFERENCES users(id) ON DELETE SET NULL,
    resolved_at     TIMESTAMP,
    resolved_by     UUID REFERENCES users(id) ON DELETE SET NULL,
    resolution_notes TEXT,

    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- One alert per (watchlist_item, conflicting_design) — natural dedupe key.
-- conflicting_design_id can be NULL post-cascade-set-null, so the unique scope
-- is partial.
CREATE UNIQUE INDEX IF NOT EXISTS uq_design_alerts_pair
    ON design_alerts_mt (watchlist_item_id, conflicting_design_id)
    WHERE conflicting_design_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_dal_org       ON design_alerts_mt(organization_id);
CREATE INDEX IF NOT EXISTS idx_dal_watchlist ON design_alerts_mt(watchlist_item_id);
CREATE INDEX IF NOT EXISTS idx_dal_status    ON design_alerts_mt(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_dal_severity  ON design_alerts_mt(organization_id, severity);
CREATE INDEX IF NOT EXISTS idx_dal_created   ON design_alerts_mt(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dal_deadline  ON design_alerts_mt(opposition_deadline) WHERE opposition_deadline IS NOT NULL;

-- ============================================
-- Rollback (uncomment to drop both tables — destructive)
-- ============================================
-- DROP TABLE IF EXISTS design_alerts_mt CASCADE;
-- DROP TABLE IF EXISTS design_watchlist_mt CASCADE;
