-- ============================================
-- Patent Watchlist + Alerts Schema
-- Adds:
--   * patent_watchlist_mt   (user-tracked patents — two watch types)
--   * patent_alerts_mt      (matches generated by the scanner)
-- Mirrors the design watchlist tables (design_watchlist_mt / design_alerts_mt)
-- but with patent-specific columns: IPC classes (not Locarno), text+embedding
-- signals only (no visual — patent figures are line drawings; deferred), and
-- a watch_type discriminator that distinguishes competitor tracking from
-- prior-art / reference monitoring.
--
-- Two watch types:
--   * 'holder'    — competitor tracking. Alerts fire on every new patent
--                   filed by the watched holder (matched by holder_id when
--                   linkable, falling back to denormalized holder_name +
--                   tpe_client_id for foreign holders).
--   * 'reference' — prior-art / similarity monitoring. Alerts fire on new
--                   patents whose title+abstract are textually or
--                   semantically similar to the reference patent (or the
--                   pasted free-text query). reference_embedding is cloned
--                   from the reference patent's title_abstract_embedding
--                   at watchlist-create time.
--
-- Idempotent: safe to run multiple times.
-- ============================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "vector";

-- ============================================
-- 1. patent_watchlist_mt — items the user is tracking
-- ============================================
CREATE TABLE IF NOT EXISTS patent_watchlist_mt (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id         UUID REFERENCES users(id) ON DELETE SET NULL,

    -- Discriminator: 'holder' or 'reference'
    watch_type      VARCHAR(20) NOT NULL
                    CHECK (watch_type IN ('holder', 'reference')),

    -- User-friendly label (e.g. "ACME Corp" or "Mechanical arm reference")
    label           VARCHAR(500) NOT NULL,
    description     TEXT,

    -- Holder-watch fields (NULL when watch_type='reference')
    holder_name           VARCHAR(500),                                -- denormalized; matching fallback
    holder_id             UUID REFERENCES holders(id) ON DELETE SET NULL,
    holder_tpe_client_id  VARCHAR(255),                                -- TPE ID for portfolio queries

    -- Reference-watch fields (NULL when watch_type='holder')
    reference_patent_id   UUID REFERENCES patents(id) ON DELETE SET NULL,
    reference_query       TEXT,                                        -- free-text fallback when no patent FK
    reference_embedding   halfvec(1024),                               -- cloned from reference_patent or computed from query

    -- Optional narrowing filters (applied to both watch types)
    ipc_classes     TEXT[] DEFAULT '{}'::TEXT[],
    kind_codes      TEXT[] DEFAULT '{}'::TEXT[],   -- e.g. ['B','A1']

    -- Customer's own application (self-conflict exclusion at scan time)
    customer_application_no VARCHAR(50),

    -- Monitoring + notification preferences
    similarity_threshold REAL DEFAULT 0.50 CHECK (similarity_threshold BETWEEN 0.0 AND 1.0),
    alert_email          BOOLEAN DEFAULT TRUE,
    alert_webhook        BOOLEAN DEFAULT FALSE,
    webhook_url          TEXT,
    alert_frequency      VARCHAR(20) DEFAULT 'daily'
                         CHECK (alert_frequency IN ('immediate','daily','weekly')),

    -- Lifecycle
    tags          TEXT[] DEFAULT '{}',
    priority      VARCHAR(10) DEFAULT 'medium' CHECK (priority IN ('low','medium','high')),
    is_active     BOOLEAN DEFAULT TRUE,
    last_scan_at  TIMESTAMP,
    created_at    TIMESTAMP DEFAULT NOW(),
    updated_at    TIMESTAMP DEFAULT NOW(),

    -- watch_type drives which columns must be set
    CONSTRAINT chk_holder_watch_has_holder
        CHECK (watch_type <> 'holder' OR (
            holder_name IS NOT NULL OR holder_id IS NOT NULL OR holder_tpe_client_id IS NOT NULL
        )),
    CONSTRAINT chk_reference_watch_has_reference
        CHECK (watch_type <> 'reference' OR (
            reference_patent_id IS NOT NULL OR reference_query IS NOT NULL
        ))
);

CREATE INDEX IF NOT EXISTS idx_pwl_org              ON patent_watchlist_mt(organization_id);
CREATE INDEX IF NOT EXISTS idx_pwl_user             ON patent_watchlist_mt(user_id);
CREATE INDEX IF NOT EXISTS idx_pwl_active           ON patent_watchlist_mt(organization_id, is_active);
CREATE INDEX IF NOT EXISTS idx_pwl_watch_type       ON patent_watchlist_mt(organization_id, watch_type);
CREATE INDEX IF NOT EXISTS idx_pwl_holder_id        ON patent_watchlist_mt(holder_id) WHERE holder_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pwl_holder_tpe       ON patent_watchlist_mt(holder_tpe_client_id) WHERE holder_tpe_client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pwl_holder_name_trgm ON patent_watchlist_mt USING GIST (holder_name gist_trgm_ops)
    WHERE holder_name IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pwl_ipc              ON patent_watchlist_mt USING GIN (ipc_classes);
CREATE INDEX IF NOT EXISTS idx_pwl_ref_vec          ON patent_watchlist_mt USING hnsw (reference_embedding halfvec_cosine_ops)
    WITH (m=16, ef_construction=200) WHERE reference_embedding IS NOT NULL;

-- ============================================
-- 2. patent_alerts_mt — matches generated by the scanner
-- ============================================
CREATE TABLE IF NOT EXISTS patent_alerts_mt (
    id                 UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    watchlist_item_id  UUID NOT NULL REFERENCES patent_watchlist_mt(id) ON DELETE CASCADE,
    user_id            UUID REFERENCES users(id) ON DELETE SET NULL,
    organization_id    UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    -- Conflict reference (denormalized so alerts survive patent row deletion)
    conflicting_patent_id        UUID REFERENCES patents(id) ON DELETE SET NULL,
    conflicting_application_no   VARCHAR(50),
    conflicting_publication_no   VARCHAR(50),
    conflicting_kind_code        VARCHAR(10),
    conflicting_title            TEXT,
    conflicting_abstract         TEXT,
    conflicting_ipc_classes      TEXT[] DEFAULT '{}',
    conflicting_holder_name      TEXT,
    conflicting_holder_country   VARCHAR(255),
    conflicting_bulletin_no      VARCHAR(20),
    conflicting_bulletin_date    DATE,
    conflicting_application_date DATE,

    -- Match diagnostics
    match_type           VARCHAR(20)   -- 'holder' | 'reference_text' | 'reference_embedding' | 'reference_hybrid'
                         CHECK (match_type IN ('holder','reference_text','reference_embedding','reference_hybrid')),
    overall_similarity_score REAL NOT NULL,      -- 0..1; holder watches always store 1.0
    text_similarity_score    REAL,
    embedding_similarity_score REAL,
    score_details            JSONB DEFAULT '{}'::jsonb,
    overlapping_ipc_classes  TEXT[] DEFAULT '{}',

    -- Lifecycle
    severity        VARCHAR(20) DEFAULT 'medium' CHECK (severity IN ('low','medium','high','critical')),
    status          VARCHAR(20) DEFAULT 'new'    CHECK (status IN ('new','seen','acknowledged','resolved','dismissed')),
    alert_type      VARCHAR(20) DEFAULT 'conflict' CHECK (alert_type IN ('conflict','event')),

    email_sent      BOOLEAN DEFAULT FALSE,
    email_sent_at   TIMESTAMP,

    acknowledged_at  TIMESTAMP,
    acknowledged_by  UUID REFERENCES users(id) ON DELETE SET NULL,
    resolved_at      TIMESTAMP,
    resolved_by      UUID REFERENCES users(id) ON DELETE SET NULL,
    resolution_notes TEXT,

    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Natural dedup: one alert per (watchlist_item, conflicting_patent).
-- conflicting_patent_id can be NULL post-cascade, so the unique scope is partial.
CREATE UNIQUE INDEX IF NOT EXISTS uq_patent_alerts_pair
    ON patent_alerts_mt (watchlist_item_id, conflicting_patent_id)
    WHERE conflicting_patent_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pal_org       ON patent_alerts_mt(organization_id);
CREATE INDEX IF NOT EXISTS idx_pal_watchlist ON patent_alerts_mt(watchlist_item_id);
CREATE INDEX IF NOT EXISTS idx_pal_status    ON patent_alerts_mt(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_pal_severity  ON patent_alerts_mt(organization_id, severity);
CREATE INDEX IF NOT EXISTS idx_pal_created   ON patent_alerts_mt(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pal_match_type ON patent_alerts_mt(organization_id, match_type);

-- ============================================
-- Rollback (uncomment to drop both tables — destructive)
-- ============================================
-- DROP TABLE IF EXISTS patent_alerts_mt CASCADE;
-- DROP TABLE IF EXISTS patent_watchlist_mt CASCADE;
